fragment WorkerFields on Worker {
  uid @include(if: $withUID)
  name @skip(if: $skipName)
  age
  gender
  stage
  favoTech
}

query Apollo($withUID: Boolean!, $skipName: Boolean = false) {
  studentsAlias: students {
    name
    age
    isMale
    classID
  }
  workerAlias: workers {
    ...WorkerFields
  }
  getWorkerById(uid: 1) {
    ...WorkerFields
  }
  variousReturnType {
    __typename
    ... on React {
      hooks
    }
    ... on Vue {
      compositionAPI
    }
  }
}
